postalserver/postal

app/views/ip_pool_rules/index.html.haml
Fairly sure this will resolve #120! 👍
=> Only display a server's IP pool name if it has an IP pool

app/views/servers/advanced.html.haml, app/views/servers/retention.html.haml
see https://github.com/atech/postal/issues/311
=> fix typos related to message retention

config/postal.defaults.yml, lib/postal/smtp_sender.rb, resource/nginx.cfg, script/install/ubuntu1604.sh
Complex pull request that affects certificate file name extensions - #98 and fixes peer verification problem - #272
=> Certificate file name extensions unified

api/structures/message_api_structure.rb
return loads and clicks on API
=> expansions activity_entries for API message

lib/postal/smtp_server/server.rb
Fixes #357
I'm however unable to replicate the exception in development mode...
=> Handle exception ETIMEDOUT in SMTP server

app/jobs/unqueue_message_job.rb
Spotted in https://github.com/atech/postal/issues/532#issuecomment-375164310
=> Fix typo in error message

api/controllers/send_api_controller.rb
not sure if this has already been picked up but just got it and thought I'd fix
=> fix send api error typo

app/assets/stylesheets/application/components/_suppression_list.scss, app/views/messages/suppressions.html.haml, config/cron.rb, config/postal.defaults.yml, lib/postal/message_db/suppression_list.rb
Resolves #815 and improves things slightly.
=> Suppression list improvements

app/views/messages/suppressions.html.haml
related to #867 
I vaguely remember flipping the logic to check my code and forgot to flip it back before committing
=> correct suppression expired check

lib/postal/dkim_header.rb
This PR resolves #1110 and #1209
=> Add common DKIM headers

script/install/ubuntu1804.sh
Same as 16.04 except that it references bionic instead of xenial in one place.
=> Ubuntu 18.04 script for quickstart

lib/postal/message_parser.rb
This satisfies all suggested links from https://github.com/atech/postal/issues/115 in HTML messages.
Most links are satisfied in plain text messages EXCEPT for (http://somesite.com) as the brackets cause the regex to miss.
A potential complete solution would be two regular expressions but I'm not sure thats the most maintainable. One would hope that most replaced links are in HTML messages.
=> fixes for link conversion

lib/postal/dkim_header.rb
There have been some reports of a small percentage of emails failing to be signed correctly. In the absence of any definitive proof of the issue, I have refactored the DKIM signing process with explicit reference to the appropriate RFC.
I'm hopeful this may well resolve the issue some people have had.
=> Refactor DKIM canonicalisation with reference to RFC

config/postal.defaults.yml, lib/postal/app_logger.rb
=> Configurable Graylog GELF protocol

lib/postal/user_creator.rb
Fix a tiny typo in the password question.
=> Remove duplicate character

lib/postal/config.rb
=> Fix smtp_server can't use ECDSA certs #1248

config/postal.defaults.yml, lib/postal/smtp_sender.rb
In reference to #1880 a clean branch.
=> Make resent-sender header optional

api/controllers/send_api_controller.rb
=> fixed typo (rfc number)

Dockerfile, Gemfile.lock, app/lib/dns_resolver.rb, app/lib/smtp_client/endpoint.rb, app/lib/smtp_client/server.rb, app/lib/smtp_client/ssl_modes.rb, app/senders/smtp_sender.rb, config/initializers/inflections.rb, config/initializers/smtp_extensions.rb, spec/lib/smtp_client/endpoint_spec.rb, spec/lib/smtp_client/server_spec.rb, spec/senders/smtp_sender_spec.rb
The SMTP sender was a bit of a mess so this tidies it all up a bit and makes it more accessible for testing.
=> Refactor SMTP Sender

.github/workflows/ci.yml, .gitignore, Dockerfile, app/helpers/application_helper.rb, app/views/layouts/application.html.haml, lib/postal/config.rb
This will allow us to display the branch an image has been built from.
=> Export branch name to container

lib/postal/config.rb
This minor update resolves #3048
=> fix: update url for v2 config
