postalserver/postal

app/models/server.rb, app/views/servers/_form.html.haml
Sice `:description` was removed from the IP pools it should display the IP pool `:name` instead of the `:description`.
Looking at 698b580db467011b7b7ae44517eafb97cc1dd43a this was overlooked.
=> Fix removed ip_pool type errors

app/views/routes/index.html.haml
The address endpoints are not mentioned on the routes UI and having an address endpoint still says you need to add endpoints before you can continue, this fixes that.
Before:
After:
=> Add address endpoints to the routes UI

app/models/outgoing_message_prototype.rb
Tested fix for #106 
If the user has enabled click tracking but doesn't send a HTML part, they don't get click tracking on their message so what I've done is consistent with how postal behaves currently.
If you decide that postal should auto generate a HTML part, that could be done in this part of the code too.
=> don't create empty parts in a multi part email

config/postal.defaults.yml, lib/postal/smtp_server/client.rb
To activate the desired option, add `strip_received_headers: true` to the `smtp_server` section of your `postal.yml` config file... then restart Postal.
=> Option to strip incoming Received headers

app/models/webhook.rb
I started to use webhooks in postal and noticed that it's not possible to use a URL with a non standard port. The regex looks a bit odd. My goal was that it shouldn't change its current behavior besides the optional port.
=> Add possibility to use other ports than 80/443 in webhooks

config/postal.defaults.yml, lib/postal/message_db/provisioner.rb, lib/postal/smtp_server/client.rb
Resolves #268.
Existing mail servers/tables needs migration. Inserting > 16M into a mediumblob column throws exception `Mysql2::Error: Data too long for column 'data' at row 1`.
Also, remember to increase [max_allowed_packet](https://mariadb.com/kb/en/library/server-system-variables/#max_allowed_packet) accordingly for MariaDB/MySQL.
=> Configurable message size limit

config/postal.defaults.yml, lib/postal/smtp_server/server.rb
Parts of #335
SSL version defaults to SSLv23, valid values (from OpenSSL::SSL::SSLContext::METHODS): `TLSv1, TLSv1_1, TLSv1_2, SSLv3, SSLv23`
Ciphers defaults to Ruby's defaults (OpenSSL::SSL::SSLContext::DEFAULT_PARAMS).
=> Configurable SMTP server OpenSSL versions and ciphers

app/views/http_endpoints/_form.html.haml, app/views/track_domains/_form.html.haml
=> Minor spelling fixes - Change seperate/seperately to separate/separately in 2 forms

app/models/webhook.rb
Fix https://github.com/atech/postal/issues/475 (please read https://github.com/atech/postal/issues/475#issuecomment-362799145)
=> missing equals sign in webhook url validation

app/views/domains/index.html.haml
Hi,
It would be awesome if the 'Add domain' button can be on top of the domains list page. 
When managing tons of domain on Postal, is annoying to go on bottom each time we want to add a domain. 
Thanks !
=> move 'Add domain' button on top of Domains page.

app/models/domain/dns_checks.rb
Addresses https://github.com/atech/postal/issues/812
As the semicolon at the end of a DKIM record is optional, some DNS software removes it.
The above change sanitizes the DKIM record before it gets checked
=> add semicolon to DKIM record data

app/views/domains/_verify_with_dns.html.haml
This resolves #893, where one could confuse `postal-verification abcdef` for a record on the subdomain `postal-verification` with contents `abcdef`
=> Make it more clear that the DNS record should point to the domain

lib/postal/http.rb
Rails Action Mailbox (released in Rails 6.0.0) uses Basic Auth to authenticate requests. Before this commit, Postal will ignore any username or password specified within the URL of an HTTP endpoint. 
By applying this commit Postal will additionally check the URL for a username/password and if found add this to the Request headers, thereby allowing users to specify an HTTP endpoint with username/password included in the URL string and allowing Postal to work with Action Mailbox.
=> Adds support for Basic Auth in HTTP Endpoint URLs

lib/postal/message_parser.rb
This is to ensure that tracking pixels are correctly added to all nested parts of the email.
Resolves #802.
=> Parse multipart/related parts recursively

lib/postal/http_sender.rb
I extended the JSON API to allow access to the `reply-to` mail header. This fixes #849.
=> Add reply_to in JSON API

lib/postal/fast_server/client.rb
A possible solution for https://github.com/postalhq/postal/issues/857#issuecomment-586310259 as this callback is removed for newer versions of OpenSSL so click tracking would not work out of the box for newer Ruby versions.
I say temporary because there may be a better way of applying the option in question.
A fix here could also be a good fit for #880 as it tries to use the same callback.
Further research definitely required, I'm creating this for future reference.
=> temporary bypass for newer OpenSSL versions

lib/postal/message_db/migrations/19_increase_links_url_size.rb
Fix for https://github.com/atech/postal/issues/668
Please note, the only way I have found to apply the migration to existing message databases is to manually run `bundle exec rake postal:migrate_message_databases`
=> add migration to increase links url size

app/models/queued_message.rb
This fixes a bug where a message is locked, and when within the same 1-second window, batchable messages are found, including the original message.
=> Do not find the original message when returning batchable messages

lib/postal/smtp_server/client.rb
This PR fixes #1182. In short, programs such as fail2ban rely on logs with events and IP addresses. This extra log entry makes it much easier to implement a regex for fail2ban.
I'm now working on a proper fail2ban jail configuration, I can commit that too if desired.
=> Add log line for failed authentication attempts

bin/postal
resolves #338 
The `run` function makes a call to `sudo` when it decides it's not the postal user and can use `sudo`.  However, it doesn't pass the environment vars along to the new context.
#338 sets `RAILS_GROUPS` but this is lost when `sudo` is called.
```
-E, --preserve-env
Indicates to the security policy that the user wishes to preserve their existing environment variables
```
=> Fix running postal command as non-postal user

config/initializers/smtp_extensions.rb
This PR fixes the check if the SMTP connection uses a secure socket. Before it directly checks the `socket` field, however this is actually an `InternetMessageIO` object which inherits from `BufferedIO`, so you need to access the `io` field from `BufferedIO` to actually access the 'real' SSL socket.
This also means we finally see the padlock next to the sent status!
Before:
After:
This fixes #1336
=> Fix check for secure socket in SMTP extensions (Fixes #1336)

README.md
* The README is listing Google Groups for support
* I simply removed Google Groups and replaced it with the link from this comment: https://github.com/postalhq/postal/issues/917#issuecomment-615157381
=> README: Replace Google Groups with Slack

lib/postal/smtp_server/server.rb
Hi team,
Some emails were being rejected with error **530 From/Sender name is not valid** but it was working with different smtp servers (google, mailgun etc) and when we looked further, we could see that the @headers variable was not getting "from" field at all even through its there in the email payload. Further investigating we figured out that the message payload has inconsistent \r\n and \n and Postal was not able to parse it correctly. We could fix it by normalizing it to convert all \n and \r\n to just use \r\n on every linebreak. Please check this pull request which fixed this issue. 
Thanks
=> Updated line split logic, normalize all linebreaks to \r\n

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml
* People are used to creating issues for support, so they will pollute issues with support questions by habit
* I created links from the issue template that will automatically guide the user to compose a new message on Github Discussions (based off of what they select)
* This also disables blank templates (so people are force to use the provided templates)
You can see the working example on my fork: https://github.com/serversideup/postal/issues/new/choose
=> Issue Templates: Add link on where to get support & suggest features

app/controllers/ip_addresses_controller.rb, app/models/ip_address.rb, app/models/queued_message.rb, app/views/ip_addresses/_form.html.haml, app/views/ip_pools/_form.html.haml, db/migrate/20210727210551_add_priority_to_ip_addresses.rb, db/schema.rb
This adds support for priorities on IP addresses thus allowing for new IPs to receive reduced levels of traffic to allow for gradual warming of IP addresses.
This is very similar (almost identical) to #833 although uses the improved method for determining the IP to use, adds some documentation and supports default priorities.
Right now, the warming process is manual but we could look at automating the increase of priority over time (as per #1103).
=> Add priorities to IP addresses

lib/postal/dkim_header.rb, spec/lib/postal/dkim_header_spec.rb
Closes #339
This resolves an issue with `DKIM-Signature` headers not being wrapped correctly. This will now wrap it at 72 characters and splits the key components over multiple lines.
=> Wrap DKIM signature headers appropriately

app/models/server.rb, config/postal.defaults.yml, lib/postal.rb, lib/postal/message_db/message.rb, lib/postal/message_inspection.rb, lib/postal/message_inspector.rb, lib/postal/message_inspectors.rb, lib/postal/message_inspectors/clamav.rb, lib/postal/message_inspectors/rspamd.rb, lib/postal/message_inspectors/spam_assassin.rb, lib/postal/spam_check.rb
This PR introduces support for `rspamd` as a spam scanning backend. There are a few things to note:
* You can add configuration for `rspamd` or `spamd` (spamassassin). If you have both, it'll use rspamd over spam assassin.
*  If you use rspamd, the thresholds for determining messages to the spam may need adjusting. You can now configure the default thresholds for new servers.
* ~With SA, we currently ignore some spam checks for outgoing messages. We don't have such a list of exclusions for rspamd at this point, we'll need to look and see what sort of messages we should be excluding and add that.~ rspamd is aware of the difference between incoming and outgoing messages and will disable certain rules for outbound messages. 
* I'm not planning to provide huge amounts of documentation on how …
=> Support for rspamd

lib/postal/smtp_server/client.rb
please see https://github.com/postalserver/postal/issues/1182#issuecomment-1360832523
auth/login gets logged, but seems cram failures were missed. 
this code has been tested with wrong user, wrong password, and the correct variants of either and works as expected  
-> but i don´t actually ruby, so feel free to rework this to wrap the message in a function or there like =)
=> fix: also log clean messages for CRAM-MD5 failures (#1182 pt2)

app/models/outgoing_message_prototype.rb
Resolves https://github.com/atech/postal/issues/375
=> message body parts should be a sub body

app/controllers/servers_controller.rb, app/models/incoming_message_prototype.rb, app/models/outgoing_message_prototype.rb, app/views/servers/advanced.html.haml, config/postal.defaults.yml, db/migrate/20240206173036_add_privacy_mode_to_servers.rb, db/schema.rb, lib/postal/received_header.rb, lib/postal/smtp_server/client.rb, spec/lib/postal/received_header_spec.rb
This allows this mode to enabled on a per-server basis. Once enabled, the IP and hostname information will be excluded from the Received headers inserted by Postal when it receives a message.
=> Privacy Mode

lib/postal/smtp_server/server.rb
This isn't used now things un in Docker.
=> Remove SMTP server reloading

app/controllers/servers_controller.rb, app/lib/message_dequeuer/initial_processor.rb, app/lib/message_dequeuer/single_message_processor.rb, app/lib/worker/process.rb, app/models/concerns/has_message.rb, app/models/queued_message.rb, app/scheduled_tasks/tidy_queued_messages_task.rb, app/views/messages/_list.html.haml, doc/config/environment-variables.md, doc/config/yaml.yml, lib/postal/config_schema.rb, spec/factories/ip_pool_factory.rb, spec/models/queued_message_spec.rb, spec/scheduled_tasks/tidy_queued_messages_task_spec.rb
Closes #2869 
This PR adds a scheduled task which will DELETE queued messages from the list if they are locked for more than 1 day (configurable).
=> Automatically remove queued messages with stale locks

Gemfile, Gemfile.lock, app/assets/stylesheets/application/components/_login_form.scss, app/assets/stylesheets/application/components/_user_list.scss, app/assets/stylesheets/application/elements/_button.scss, app/assets/stylesheets/application/elements/_label.scss, app/controllers/sessions_controller.rb, app/controllers/user_controller.rb, app/models/concerns/has_authentication.rb, app/models/user.rb, app/views/sessions/new.html.haml, app/views/user/edit.html.haml, app/views/users/_form.html.haml, app/views/users/index.html.haml, config/application.rb, config/initializers/inflections.rb, config/initializers/omniauth.rb, config/routes.rb, db/migrate/20240311205229_add_oidc_fields_to_user.rb, db/schema.rb, doc/config/environment-variables.md, doc/config/yaml.yml, lib/postal/config_schema.rb, lib/postal/yaml_config_exporter.rb, spec/factories/user_factory.rb, spec/models/user/authentication_spec.rb, spec/models/user/oidc_spec.rb, spec/models/user_spec.rb
Closes #2870 
This PR adds support for OpenID Connect as a means for authenticating to the Postal web interface. This provides a higher level of security than the built-in authentication mechanism by allowing you to take advantage of additional protections offered by an external Identity provider (like two factor authentication).
=> OpenID Connect Support

doc/config/environment-variables.md, doc/config/yaml.yml, lib/postal/config_schema.rb
OIDC scopes should be an array of strings, the current default value seems wrong and fails with authelia, I get those logs:
```
omniauth: (oidc) Request phase initiated.
"POST /auth/oidc HTTP/1.1" 302 274 0.0484
omniauth: (oidc) Callback phase initiated.
omniauth: (oidc) Authentication failure! invalid_scope: OmniAuth::Strategies::OpenIDConnect::CallbackError, invalid_scope | The requested scope is invalid, unknown, or malformed. The OAuth 2.0 Client is not allowed to request scope 'openid,email'.
```
=> fix: oidc scopes are invalid when concatenated
